import type { Metadata } from "next";
import { outfit, italiana,cinzel } from "./font";
import "./globals.css";
import StateProvider from "../context/StateContext";
import Navbar from "@/components/Navs/Navbar";
import Footer from "@/components/Footer";
import React from "react";



export const metadata: Metadata = {
  title: "Interior Architecture",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${outfit.variable} ${italiana.variable} ${cinzel.variable}`}
    >
      <body className="font-outfit bg-gray-900 text-white">
        <StateProvider>
          <Navbar />
          {children}

          <Footer />
        </StateProvider>
      </body>
    </html>
  );
}
